#config map:
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: mongodb
#data:
#  ME_CONFIG_BASICAUTH_ENABLED: "true"

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  MYSQL_DATABASE: "maindb"
