#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    app: nginx
#  name: nginx
#spec:
#  replicas: 2 #previous: 1
#  selector:
#    matchLabels:
#      app: nginx
#  strategy: {}
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#      - image: nginx:1.29
#        name: nginx
#        resources: {}
#status: {}


###Task 4

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodatabase
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: ME_CONFIG_MONGODB_AUTH_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: ME_CONFIG_MONGODB_AUTH_PASSWORD        
        resources: {0}   
      - name: mongo-express
        image: mongo-express:latest
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb      # nazwa kontenera Mongo w tym samym Podzie
          - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: ME_CONFIG_MONGODB_AUTH_DATABASE
          - name: ME_CONFIG_MONGODB_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: ME_CONFIG_MONGODB_AUTH_USERNAME
          - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: ME_CONFIG_MONGODB_AUTH_PASSWORD
        envFrom:
          - configMapRef:
              name: mongodb
        resources: {0}
        

