#service:
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service
#spec:
#  type: NodePort
#  selector:
#    app: nginx
#  ports:
#  - port: 80
#    targetPort: 80
#    nodePort: 30036
#    protocol: TCP

#Task4:
#apiVersion: v1
#kind: Service
#metadata:
#  name: mongo
#spec:
#  type: NodePort
#  selector:
#    app: mongodb
#  ports:
#  - port: 27017
#    targetPort: 27017
#    protocol: TCP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mongo-express
#spec:
#  type: NodePort
#  selector:
#    app: mongo-express
#  ports:
#  - port: 8081
#    targetPort: 8081
#    nodePort: 30081


#MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: triple-stack
spec:
  selector:
    app: mysql
  ports:
  - port: 3306

---
#Backend
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: triple-stack
spec:
  selector:
    app: myapp-backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

---
#frontend
  apiVersion: v1
  kind: Service
  metadata:
    name: frontend-service
    namespace: triple-stack
  spec:
    selector:
      app: myapp-frontend
    ports:
    - port: 80
      targetPort: 80
    type: NodePort